---
title: "OASIS Longitudinal Analysis"
output: html_document
---

## Load Data

```{r load, message=FALSE}
library(tidyverse)
library(here)

oasis <- read_csv(here("data", "raw", "oasis_longitudinal.csv"))

glimpse(oasis)
```
##  Plot
```{r}

```

```{r plot}
ggplot(oasis, aes(x = `MR Delay`, y = nWBV, colour = Group)) +
  geom_line(aes(group = `Subject ID`), alpha = 0.3) +
  geom_smooth(method = "lm", se = FALSE) +
  labs(
    title = "Brain Volume Over Time by Group",
    x = "Days since first visit",
    y = "Normalised Whole Brain Volume"
  ) +
  theme_minimal()
```


```{r}
install.packages("lme4")
install.packages("lmerTest")
```
## The Null Model

```{r null_model, message=FALSE}
library(lme4)
library(lmerTest)

null_model <- lmer(nWBV ~ 1 + (1 | `Subject ID`), data = oasis)

summary(null_model)
```


## Adding Time (Level-1 Predictor)

```{r time_model, message=FALSE}
time_model <- lmer(nWBV ~ `MR Delay` + (1 | `Subject ID`), data = oasis)

summary(time_model)
```


## Adding Group (Level-2 Predictor)

```{r group_model, message=FALSE}
group_model <- lmer(nWBV ~ `MR Delay` + Group + (1 | `Subject ID`), data = oasis)

summary(group_model)
```
## Random Slope Model

```{r random_slope, message=FALSE}
slope_model <- lmer(nWBV ~ `MR Delay` + Group + (1 + `MR Delay` | `Subject ID`), data = oasis)

summary(slope_model)
```
